const express   = require("express");
const cors      = require("cors");
const dotenv    = require("dotenv");
const path      = require("path");
const connectDB = require("./config/db");
dotenv.config(); connectDB();
const app=express(), PORT=process.env.PORT||5000;
app.use(cors({ origin:["http://localhost:3000","http://127.0.0.1:3000","http://localhost:5500","http://127.0.0.1:5500","https://akshatj0707.github.io",process.env.FRONTEND_URL].filter(Boolean), credentials:true }));
app.use(express.json({ limit:"20mb" }));
app.use(express.static(path.join(__dirname,"../public")));
const { statsRouter, usersRouter } = require("./routes/stats");
app.use("/api/auth",       require("./routes/auth"));
app.use("/api/students",   require("./routes/students"));
app.use("/api/attendance", require("./routes/attendance"));
app.use("/api/stats",      statsRouter);
app.use("/api/users",      usersRouter);
app.get("/health",(req,res)=>{ const m=require("mongoose"); res.json({ status:"ok", db:m.connection.readyState===1?"connected":"disconnected", dbName:m.connection.name, uptime:Math.floor(process.uptime()), version:"3.0.0" }); });
app.get("*",(req,res)=>{ if(req.path.startsWith("/api")) return res.status(404).json({ success:false, error:"Not found" }); res.sendFile(path.join(__dirname,"../public/index.html")); });
app.use((err,req,res,next)=>res.status(err.status||500).json({ success:false, error:err.message||"Server Error" }));
const server=app.listen(PORT,()=>{ console.log(`\n🎓 College Attendance System`); console.log(`   http://localhost:${PORT}\n`); });
process.on("SIGTERM",()=>server.close(()=>process.exit(0)));
process.on("SIGINT", ()=>server.close(()=>process.exit(0)));